### ISSUE TITLE
Question: How to read live temperature values?

### ISSUE THREAD

**Issue by Grandma-Betty** [Lifeina/lifeinabox-communication-protocol#1]
Dear Lifeinabox team
This is not really an issue but more a support question.
I have just received my brandnew lifeinabox device which will be attached permanently to 230V power at my home. Now instead of using the app, I would like to read the live temperature values with an ESP32 device so I can log the lifeinabox temperaures values with my homeautomation system ("Home Assistant" in my case) via [ESPHome BLE client](https://esphome.io/components/sensor/ble_client).
Unfortunately the only information you are providing on Github is the address for getting the battery status and the historical temparature for the last couple of hours, but not the live temperature values. Could you please also tell on which address to get the live temperature value?
Thank you very much in advance!

**Comment by nicodinh** [comment]
> Could you please also tell on which address to get the live temperature value? Thank you very much in advance!

Hi @Grandma-Betty, there's no way to retrieve the data in real time.

When the temperature value changes, the history is updated.

The history must be retrieved periodically to simulate real time.

**Comment by nicodinh** [comment]
> Could you _please_ kindly help me out with this? I feel I am so close. Thanks a bunch in advance!

To read you need to write, something like that

- Temperature : 
```
- ble_client.ble_write:
              id: LifeinaBox
              service_uuid: 0000fee9-0000-1000-8000-00805f9b34fb
              characteristic_uuid: d44bc439-abfd-45a2-b575-925416129601
              value: [0xaa, 0x8f, 0x06, 0x55]
```
- Battery
```
- ble_client.ble_write:
              id: LifeinaBox
              service_uuid: 0000fee9-0000-1000-8000-00805f9b34fb
              characteristic_uuid: d44bc439-abfd-45a2-b575-925416129601
              value: [0xaa, 0x8e, 0xff, 0x55]
```
